### ISSUE TITLE
Couldn't find the 'node' binary

### ISSUE THREAD

**Issue by FrancisGong** [pawelgrzybek/Github-Search#1]
Hi, I am using masOS Sierra. When I type github XXX, it shows 
<img width="614" alt="screen shot 2017-02-27 at 12 49 44" src="https://cloud.githubusercontent.com/assets/22341096/23349132/4fdfe902-fceb-11e6-8ee5-f0406944b5b7.png">

**Comment by pawelgrzybek** [comment]
Hi.

It is easy to fix. Documentation to this workflow says:

> To make it work, node needs to be installed on your machine. To confirm that you have it installed open a Terminal app and type node -v that shows a version on installed interpreter or alert "command not found" which means that you need to install it.

Just go to https://nodejs.org/en/ and install node on your machine. All done :-)

**Comment by FrancisGong** [comment]
Wow, thanks a lot.
