### ISSUE TITLE
Does not work with Alfred 3.3.1

### ISSUE THREAD

**Issue by pkuczynski** [pawelgrzybek/Github-Search#2]
Output from debugger:

```
workflows/user.workflow.0F127BCF-F7C4-4F69-9E82-EB1AD936FB7A/index.js:2
const fetch = require('node-fetch');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by pawelgrzybek** [comment]
Cześć Piotrze. Jaka jest wersja node?

**Comment by pawelgrzybek** [comment]
```
node -v
```

**Comment by pkuczynski** [comment]
Wiem jak sprawdzic node ;) W domu mam 7.5 i dziala. W pracy zdaje sie 0.12? Jutro ci sprawdze...

**Comment by pawelgrzybek** [comment]
Wińmy tu więc starą wersję node która nie kojarzy co to const :) Od wersji node 4 wszytko powinno śmigać :)

Pozdrawiam

**Comment by pkuczynski** [comment]
Tak jak myslalem w pracy mam 0.12.18. Niestety nie moge zmienic wersji na wyzsza. Nie da sie zrobic tak, zeby dzialalo ze strasza?

**Comment by pawelgrzybek** [comment]
A rozumiem. Jasne że się da. Poprawię to dziś w ciągu dnia i zaktualizuje repo i workflows na packal'u. Jak na szybko chcesz poprawić samemu, w pliku index.js zmień wszystkie `const` na `var` :)

**Comment by pawelgrzybek** [comment]
https://github.com/pawelgrzybek/Alfred-github-search/blob/master/index.js#L2

https://github.com/pawelgrzybek/Alfred-github-search/blob/master/index.js#L8

**Comment by pkuczynski** [comment]
Spoko, moge poczekac :) Dzieki za pomoc!
