### ISSUE TITLE
Does not work with my setup.

### ISSUE THREAD

**Issue by roelvan** [pawelgrzybek/Github-Search#3]
![09-14-2017-11 47 36](https://user-images.githubusercontent.com/2583837/30423237-93403442-9942-11e7-8248-88ae81daad1a.jpg)

I use nvm and Alfred v3.4.1

**Comment by pawelgrzybek** [comment]
Hi.

Quick spot! It is using the npms API. Hopefully it is just an temporary issue with their API.

https://npms.io/search?q=react
