### ISSUE TITLE
A small request

### ISSUE THREAD

**Issue by Treldo** [pawelgrzybek/Github-Search#4]
Hi,

I found that the speed of "github-search" is not immediate under my web environment, the delay of new keyword is clearly. So how can I use a hotkey such as "Return" as the symbol of search action instead of the **Instant search** ?

Thank you !

**Comment by pawelgrzybek** [comment]
I am afraid that it is not possible with Alfred. Return confirm an action (Alfred disappears). Github API call happens on every keydown event. I am it is hard to make this change to work to your expectations :(

**Comment by Treldo** [comment]
Thanks for your reply !

I think I may understand what you mean, I will  modify the **Language:Run Behaviour** to improve the situation.
